name: dictaphone

services:
  # docker start -p 7860:7860 -v /home/azureuser/vaults/obsidian/001\ Inbox:/vault -v .:/usr/src/app -v /home/azureuser/recordings:/recordings -e DEVICE="Azure" -e OPENAI_API_KEY=$(OPENAI_API_KEY) --restart always gradio-dictaphone:latest
  # gradio:
  #   container_name: dict-gradio
  #   image: gradio-dictaphone:latest
  #   ports:
  #     - "7860:7861"
  #   #restart: always
  #   volumes:
  #     - /home/azureuser/vaults/obsidian/001\ Inbox:/vault
  #     - .:/usr/src/app
  #     - /home/azureuser/recordings:/recordings
  #   environment:
  #     - DEVICE="MBP"
  #     - OPENAI_API_KEY=""
  #     - USER="Robert"
  #     - GRADIO_SERVER_NAME="0.0.0.0"
  #     - GRADIO_SERVER_PORT=7860

  redis:
    container_name: dict-redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    restart: always
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  caddy:
    container_name: dict-caddy
    image: caddy:latest
    network_mode: host
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  authelia:
    image: authelia/authelia
    container_name: dict-authelia
    restart: always
    volumes:
      - ./authelia_config:/config
    ports:
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000

volumes:
  caddy-data:
  caddy-config:

networks:
  searxng:
    ipam:
      driver: default
